### POST USER добавление админа (регистрация)
POST localhost:8080/user
content-type: application/json

{
  "fio" : "Hrenov Hren Hrenych",
  "email" : "hren@mail.ru",
  "phone" : "899978651234",
  "passport" : "12345678",
  "password" : "123",
  "roles" : "ROLE_ADMIN"
}

### POST USER добавление пользователя (регистрация)
POST localhost:8080/user
content-type: application/json

{
  "fio" : "Petrov Petr Petrovich",
  "email" : "hren1@mail.ru",
  "phone" : "899978651235",
  "passport" : "12345679",
  "password" : "1234",
  "roles" : "ROLE_USER"
}

### GET Users incorrect
GET localhost:8080/user

### GET Users incorrect
GET localhost:8080/user
Authorization: Basic hren1@mail.ru 1234

### GET Users список пользователей зарегистрированных
GET localhost:8080/user
Authorization: Basic hren@mail.ru 123



### POST CARPlace добавить салон (страница админа)
POST localhost:8080/carplace
content-type: application/json

{
  "country" : "Russia",
  "city" : "Moscow",
  "address" :"Red Square",
  "phone" : "+7 999 999 99 99"
}


### POST CAR добавить машину (страница админа)
POST localhost:8080/car/1
content-type: application/json

{
  "category" : "Luxury",
  "brand" : "Mercedes-AMG",
  "model" :"E63",
  "year" : 2021,
  "available" : "false",
  "price" : 2000
}


### GET получение машины (отображение у пользователя и админа)
GET localhost:8080/car/category/Luxury



### POST order добавление заказа (при введеных данных и выбранной машине создается заказ)
POST localhost:8080/order/1
content-type: application/json

{
  "countDays" : 5
}

### GET all order by id user (получение заказа для пользователя по его ID)
GET localhost:8080/order/1 (выводит заказы для пользователя)

